version:

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -lc "bundle exec rails db:prepare && rm -f tmp/pids/server.pid && ./bin/dev"
    tty: true
    stdin_open: true
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      REDIS_URL: "redis://redis:6379/0"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started


  db:
    image: postgres:16 #最新のバージョン確認
    environment:
      TZ: Asia/Tokyo
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5


  worker: # Sidekiq
    build:
      context: .
    command: bash -lc "bundle exec sidekiq -C config/sidekiq.yml" #ログインシェルで、Bundler 管理下の Sidekiq を、指定の設定で起動
    environment:
      RAILS_ENV: development
      REDIS_URL: "redis://redis:6379/0"
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  postgres_data:
  redis_data:
  bundle_cache:
  node_modules: